## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [28]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
# Type your solution here
import pandas as pd
import numpy as np
#1:
df = pd.DataFrame(data)
print(df)

#2:
print(df[((df.job == 'teacher') | (df.job == 'psychologist')) & (df.num_cars > df.family_size)])


#3:
family = df['family_size']
cars = df['num_cars']
answer = np.logical_and( family <= 2, cars >= 1)
print(df.name[answer])

#4:
print(df['job'].nunique())




**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [82]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [112]:
# Type your solution here
#print(fruit)
#print(weights)

applesAverage = (weights[fruit == "apple"]).mean()
print(applesAverage)

bananasAverage = (weights[fruit == "banana"]).mean()
print(bananasAverage)

carrotAverage = (weights[fruit == "carrot"]).mean()
print(carrotAverage)


4.0
8.333333333333334
4.666666666666667


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [8]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [16]:
# Type your solution here
np.argsort(course_name)

for name in course_name:
  if name[0] == 'P':
    print(name, " starts with P")


Python  starts with P
PHP  starts with P


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [117]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [125]:
# Type your solution here
#reverse 
print(student_id)
print(np.flip(student_id))

#get three largest values of student_ID array
#first need to sort it
sorted = np.sort(student_id)
flipped = np.flip(sorted)
print(flipped[1:4])


[1023 5202 6230 1671 1682 5241 4532]
[4532 5241 1682 1671 6230 5202 1023]
[5241 5202 4532]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [140]:
# Type your solution here

# Hint: you can use arange to start off
array3 = np.arange(0, 100, 3)
sum3 = array3.sum()

array5 = np.arange(0, 100, 5)
sum5 = array5.sum()

sum3 + sum5


2633

**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [19]:
import numpy as np

array = np.arange(12).reshape(3,4)
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [22]:
# Type your solution here
array[:, [1, 0]]=array[:, [0, 1]]
print(array)

array[[1, 0], :]=array[[0, 1], :]
print(array)




[[ 1  0  2  3]
 [ 5  4  6  7]
 [ 9  8 10 11]]
[[ 5  4  6  7]
 [ 1  0  2  3]
 [ 9  8 10 11]]
